[package]
name = "reth-scroll-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-consensus.workspace = true
alloy-primitives.workspace = true

# reth
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-consensus-common.workspace = true
reth-ethereum-consensus.workspace = true
reth-execution-types.workspace = true
# imported in order to pull in the reth-codec feature for reth-ethereum-primitives
reth-primitives = { workspace = true, features = ["reth-codec"] }
reth-primitives-traits.workspace = true

# scroll
reth-scroll-primitives = { workspace = true, features = ["serde", "reth-codec"] }
scroll-alloy-hardforks.workspace = true

# misc
thiserror.workspace = true
tracing.workspace = true

[package.metadata.cargo-udeps.ignore]
normal = ["reth-primitives"]
