[package]
name = "scroll-alloy-network"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
alloy-provider = { workspace = true, default-features = false }

scroll-alloy-consensus = { workspace = true, default-features = false }
scroll-alloy-rpc-types = { workspace = true, default-features = false }

# alloy
alloy-consensus = { workspace = true, default-features = false }
alloy-network = { workspace = true, default-features = false }
alloy-primitives = { workspace = true, default-features = false }
alloy-rpc-types-eth = { workspace = true, default-features = false }
alloy-signer = { workspace = true, default-features = false }

[features]
std = [
    "alloy-consensus/std",
    "alloy-primitives/std",
    "alloy-rpc-types-eth/std",
    "scroll-alloy-consensus/std",
    "scroll-alloy-rpc-types/std",
]
