[package]
name = "scroll-alloy-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-primitives.workspace = true

# revm
revm.workspace = true

# scroll
revm-scroll.workspace = true

# scroll
scroll-alloy-consensus.workspace = true
scroll-alloy-hardforks.workspace = true

# misc
auto_impl.workspace = true
serde = { workspace = true, default-features = false, features = ["derive"], optional = true }

[dev-dependencies]
eyre.workspace = true

[features]
std = [
    "alloy-evm/std",
    "alloy-primitives/std",
    "revm-scroll/std",
    "revm/std",
    "serde/std",
    "alloy-consensus/std",
    "alloy-eips/std",
]
serde = [
    "dep:serde",
    "alloy-primitives/serde",
    "revm-scroll/serde",
    "revm/serde",
    "alloy-eips/serde",
    "alloy-consensus/serde",
    "scroll-alloy-consensus/serde",
    "scroll-alloy-hardforks/serde",
]
