[package]
name = "scroll-reth-mpt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-cli-util.workspace = true
reth-node-builder.workspace = true
reth-provider.workspace = true

# scroll
reth-scroll-cli.workspace = true
reth-scroll-node.workspace = true

# misc
clap = { workspace = true, features = ["derive", "env"] }

[features]
scroll = [
	"reth-provider/scroll",
	"reth-scroll-cli/scroll",
]
mpt = [
	"reth-scroll-cli/mpt",
	"reth-scroll-node/mpt",
]
skip-state-root-validation = [
	"reth-node-builder/skip-state-root-validation",
	"reth-scroll-node/skip-state-root-validation"
]
optimism = [
	"reth-provider/optimism",
	"reth-scroll-cli/optimism",
	"reth-scroll-node/optimism"
]

[[bin]]
name = "scroll-reth-mpt"
path = "src/main.rs"
required-features = ["mpt", "skip-state-root-validation", "scroll"]
