[package]
name = "reth-scroll-revm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# revm
revm = { version = "19.2.0", default-features = false }

[features]
default = ["std"]
dev = ["revm/dev"]
arbitrary = ["revm/arbitrary"]
asm-keccak = ["revm/asm-keccak"]
c-kzg = ["revm/c-kzg"]
optimism = ["revm/optimism"]
serde = ["revm/serde"]
scroll = ["revm/scroll-poseidon-codehash"]
test-utils = ["revm/test-utils"]
std = ["revm/std"]

blst = ["revm/blst"]
optional_block_gas_limit =  ["revm/optional_block_gas_limit"]
optional_eip3607 = ["revm/optional_eip3607"]
optional_no_base_fee = ["revm/optional_no_base_fee"]
secp256k1 = ["revm/secp256k1"]
