[package]
name = "scroll-alloy-consensus"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# Alloy
alloy-rlp.workspace = true
alloy-eips.workspace = true
alloy-consensus.workspace = true
alloy-primitives = { workspace = true, features = ["rlp"] }

# misc
derive_more = { workspace = true, features = ["display"] }

# arbitrary
arbitrary = { workspace = true, features = ["derive"], optional = true }

reth-codecs = { workspace = true, optional = true }
reth-codecs-derive = { workspace = true, optional = true }

# required by reth-codecs
modular-bitfield = { workspace = true, optional = true }

# serde
alloy-serde = { workspace = true, optional = true }
serde = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
rand.workspace = true
bincode.workspace = true
serde_json.workspace = true
arbitrary = { workspace = true, features = ["derive"] }
alloy-primitives = { workspace = true, features = ["rand", "arbitrary"] }
reth-codecs = { workspace = true, features = ["test-utils"] }
proptest-arbitrary-interop.workspace = true
proptest.workspace = true
test-fuzz.workspace = true

[features]
default = [
    "reth-codec",
    "std",
]
std = [
    "serde/std",
    "alloy-primitives/std",
    "reth-codecs/std",
    "alloy-consensus/std",
    "alloy-eips/std",
    "alloy-rlp/std",
    "alloy-serde/std",
    "proptest/std",
    "rand/std",
    "derive_more/std",
    "serde_json/std",
]
k256 = [
    "alloy-primitives/k256",
    "alloy-consensus/k256",
]
kzg = [
    "alloy-eips/kzg",
    "alloy-consensus/kzg",
    "std",
]
reth-codec = [
    "dep:reth-codecs",
    "dep:reth-codecs-derive",
    "modular-bitfield",
    "std",
]
arbitrary = [
    "std",
    "dep:arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-consensus/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-serde/arbitrary",
    "reth-codecs/arbitrary",
    "alloy-primitives/rand",
]
serde = [
    "dep:serde",
    "dep:alloy-serde",
    "alloy-primitives/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "rand/serde",
    "reth-codecs/serde",
]
serde-bincode-compat = [
    "alloy-consensus/serde-bincode-compat",
    "alloy-eips/serde-bincode-compat",
]
