[package]
name = "reth-scroll-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-db = { workspace = true, features = ["scroll-alloy-traits"] }
reth-cli.workspace = true
reth-cli-commands.workspace = true
reth-cli-runner.workspace = true
reth-consensus.workspace = true
reth-node-builder.workspace = true
reth-node-core.workspace = true
reth-node-metrics.workspace = true
reth-tracing.workspace = true

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-evm.workspace = true
reth-scroll-primitives.workspace = true
scroll-alloy-consensus = { workspace = true, optional = true }

# misc
eyre.workspace = true
clap.workspace = true
proptest = { workspace = true, optional = true }
tracing.workspace = true

[features]
dev = [
    "dep:proptest",
    "dep:scroll-alloy-consensus",
    "reth-cli-commands/arbitrary",
]
