[package]
name = "reth-scroll-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-codecs = { workspace = true, optional = true }
reth-primitives-traits = { workspace = true, features = ["scroll-alloy-traits"] }
reth-zstd-compressors = { workspace = true, optional = true }

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# revm
revm-context.workspace = true

# scroll
scroll-alloy-consensus.workspace = true
scroll-alloy-evm.workspace = true
revm-scroll.workspace = true

# codec
bytes = { workspace = true, optional = true }
modular-bitfield = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

# misc
derive_more.workspace = true
once_cell.workspace = true
rand = { workspace = true, optional = true }

# test
arbitrary = { workspace = true, features = ["derive"], optional = true }
proptest = { workspace = true, optional = true }
secp256k1 = { workspace = true, optional = true }

[dev-dependencies]
proptest-arbitrary-interop.workspace = true
reth-codecs = { workspace = true, features = ["test-utils"] }
rstest.workspace = true
proptest.workspace = true
secp256k1 = { workspace = true, features = ["rand"] }
rand.workspace = true

[features]
default = ["std"]
std = [
    "serde?/std",
    "scroll-alloy-consensus/std",
    "alloy-consensus/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "bytes?/std",
    "reth-primitives-traits/std",
    "reth-zstd-compressors?/std",
    "reth-codecs?/std",
    "derive_more/std",
    "once_cell/std",
    "proptest?/std",
    "serde?/std",
    "rand?/std",
    "secp256k1?/std",
    "revm-scroll/std",
    "revm-context/std",
    "alloy-evm/std",
    "scroll-alloy-evm/std",
]
reth-codec = [
    "dep:reth-codecs",
    "std",
    "dep:proptest",
    "dep:arbitrary",
    "reth-primitives-traits/reth-codec",
    "scroll-alloy-consensus/reth-codec",
    "dep:bytes",
    "dep:modular-bitfield",
    "dep:reth-zstd-compressors",
]
serde = [
    "dep:serde",
    "scroll-alloy-consensus/serde",
    "secp256k1?/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "bytes?/serde",
    "rand?/serde",
    "reth-codecs?/serde",
    "reth-primitives-traits/serde",
    "revm-scroll/serde",
    "revm-context/serde",
    "scroll-alloy-evm/serde",
]
serde-bincode-compat = [
    "alloy-consensus/serde-bincode-compat",
    "alloy-eips/serde-bincode-compat",
    "reth-primitives-traits/serde-bincode-compat",
    "scroll-alloy-consensus/serde-bincode-compat",
]
arbitrary = [
    "dep:arbitrary",
    "dep:secp256k1",
    "secp256k1?/rand",
    "rand",
    "alloy-consensus/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-primitives/arbitrary",
    "reth-codecs?/arbitrary",
    "reth-primitives-traits/arbitrary",
    "scroll-alloy-consensus/arbitrary",
]
