[package]
name = "reth-scroll-primitives"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-codecs = { workspace = true, optional = true }
reth-primitives-traits = { workspace = true, features = ["scroll-alloy-traits"] }
reth-zstd-compressors = { workspace = true, optional = true }

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-primitives.workspace = true
alloy-rlp.workspace = true

# scroll
scroll-alloy-consensus.workspace = true

# codec
bytes = { workspace = true, optional = true }
modular-bitfield = { workspace = true, optional = true }
serde = { workspace = true, optional = true }

# misc
once_cell.workspace = true

# test
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
reth-codecs = { workspace = true, features = ["test-utils"] }
rstest.workspace = true
rand.workspace = true

[features]
default = ["std"]
std = [
    "serde?/std",
    "scroll-alloy-consensus/std",
    "alloy-consensus/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rlp/std",
    "bytes?/std",
    "reth-primitives-traits/std",
    "reth-zstd-compressors?/std",
    "reth-codecs?/std",
    "once_cell/std",
    "serde?/std",
]
reth-codec = [
    "dep:reth-codecs",
    "std",
    "dep:arbitrary",
    "reth-primitives-traits/reth-codec",
    "scroll-alloy-consensus/reth-codec",
    "dep:bytes",
    "dep:modular-bitfield",
    "dep:reth-zstd-compressors",
]
serde = [
    "dep:serde",
    "scroll-alloy-consensus/serde",
    "alloy-consensus/serde",
    "alloy-eips/serde",
    "alloy-primitives/serde",
    "bytes?/serde",
    "reth-codecs?/serde",
    "reth-primitives-traits/serde",
    "rand/serde",
]
serde-bincode-compat = [
    "alloy-consensus/serde-bincode-compat",
    "alloy-eips/serde-bincode-compat",
    "reth-primitives-traits/serde-bincode-compat",
    "scroll-alloy-consensus/serde-bincode-compat",
]
arbitrary = [
    "dep:arbitrary",
    "alloy-consensus/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-primitives/arbitrary",
    "reth-codecs?/arbitrary",
    "reth-primitives-traits/arbitrary",
    "scroll-alloy-consensus/arbitrary",
]
