[package]
name = "reth-scroll-node"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-rpc-eth-types.workspace = true
reth-eth-wire-types.workspace = true
reth-evm = { workspace = true, features = ["scroll-alloy-traits"] }
reth-network.workspace = true
reth-node-api.workspace = true
reth-node-types.workspace = true
reth-node-builder.workspace = true
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-provider.workspace = true
reth-tracing.workspace = true
reth-transaction-pool.workspace = true
reth-trie-db.workspace = true

# revm
revm = { workspace = true, features = ["c-kzg"] }

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-rpc-types-engine.workspace = true

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-consensus.workspace = true
reth-scroll-engine-primitives.workspace = true
reth-scroll-evm.workspace = true
reth-scroll-forks.workspace = true
reth-scroll-payload.workspace = true
reth-scroll-primitives = { workspace = true, features = ["serde", "serde-bincode-compat"] }
reth-scroll-rpc.workspace = true
scroll-alloy-consensus.workspace = true
scroll-alloy-evm.workspace = true
scroll-alloy-rpc-types-engine.workspace = true

# alloy
alloy-primitives.workspace = true

# misc
eyre.workspace = true
thiserror.workspace = true
tokio.workspace = true

[features]
default = ["reth-codec"]
reth-codec = [
    "reth-primitives/reth-codec",
    "reth-primitives-traits/reth-codec",
    "reth-scroll-primitives/reth-codec",
]
skip-state-root-validation = [
    "reth-provider/skip-state-root-validation",
    "reth-node-builder/skip-state-root-validation",
]
