[package]
name = "reth-trie-common"
version.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
description = "Commonly used types for trie usage in reth."

[lints]
workspace = true

[dependencies]
reth-primitives-traits = { workspace = true, features = ["serde"] }
reth-codecs.workspace = true

alloy-primitives.workspace = true
alloy-rlp = { workspace = true, features = ["arrayvec"] }
alloy-trie = { workspace = true, features = ["serde"] }
alloy-consensus.workspace = true
alloy-genesis.workspace = true

# revm-primitives scroll re-export
revm-primitives = { package = "reth-scroll-revm", path = "../../scroll/revm" }
reth-scroll-primitives = { workspace = true, optional = true }

bytes.workspace = true
derive_more.workspace = true
serde.workspace = true
itertools.workspace = true
nybbles = { workspace = true, features = ["serde", "rlp"] }

# `test-utils` feature
hash-db = { version = "=0.15.2", optional = true }
plain_hasher = { version = "0.2", optional = true }
arbitrary = { workspace = true, features = ["derive"], optional = true }

[dev-dependencies]
alloy-primitives = { workspace = true, features = ["getrandom"] }
arbitrary = { workspace = true, features = ["derive"] }
proptest.workspace = true
proptest-arbitrary-interop.workspace = true
hash-db = "=0.15.2"
plain_hasher = "0.2"

reth-scroll-primitives.workspace = true

[features]
test-utils = [
	"dep:plain_hasher",
	"dep:hash-db",
	"arbitrary",
	"reth-primitives-traits/test-utils",
	"reth-codecs/test-utils",
	"revm-primitives/test-utils"
]
arbitrary = [
	"alloy-trie/arbitrary",
	"dep:arbitrary",
	"reth-primitives-traits/arbitrary",
	"alloy-consensus/arbitrary",
	"alloy-primitives/arbitrary",
	"nybbles/arbitrary",
	"revm-primitives/arbitrary",
	"reth-codecs/arbitrary",
	"reth-scroll-primitives?/arbitrary"
]
scroll = [
	"reth-primitives-traits/scroll",
	"dep:reth-scroll-primitives",
	"revm-primitives/scroll"
]
