[package]
name = "reth-scroll-chainspec"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "EVM chain spec implementation for scroll."

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec = { workspace = true, features = ["scroll"] }
reth-ethereum-forks = { workspace = true, default-features = false }
reth-network-peers = { workspace = true, default-features = false }
reth-primitives-traits = { workspace = true, default-features = false }
reth-trie-common = { workspace = true, default-features = false }

# scroll
reth-scroll-forks = { workspace = true, default-features = false }
scroll-alloy-hardforks = { workspace = true, default-features = false }

# ethereum
alloy-chains = { workspace = true, default-features = false }
alloy-genesis = { workspace = true, default-features = false }
alloy-primitives = { workspace = true, default-features = false }
alloy-consensus = { workspace = true, default-features = false }
alloy-eips = { workspace = true, default-features = false }
alloy-serde = { workspace = true, default-features = false }

# io
serde_json = { workspace = true, default-features = false }
serde = { workspace = true, default-features = false, features = ["derive"] }

# misc
derive_more = { workspace = true, default-features = false }
once_cell = { workspace = true, default-features = false }

[dev-dependencies]
alloy-genesis.workspace = true
reth-chainspec = { workspace = true, features = ["test-utils"] }

[features]
default = ["std"]
std = [
    "alloy-chains/std",
    "alloy-genesis/std",
    "alloy-primitives/std",
    "alloy-eips/std",
    "alloy-serde/std",
    "reth-chainspec/std",
    "reth-ethereum-forks/std",
    "reth-primitives-traits/std",
    "reth-scroll-forks/std",
    "reth-trie-common/std",
    "alloy-consensus/std",
    "once_cell/std",
    "serde/std",
    "derive_more/std",
    "reth-network-peers/std",
    "serde_json/std",
    "scroll-alloy-hardforks/std",
]
