[package]
name = "reth-scroll-trie"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-trie.workspace = true

# alloy
alloy-primitives.workspace = true
alloy-trie = { workspace = true, features = ["serde"] }

# misc
poseidon-bn254 = { workspace = true, features = ["bn254"] }
tracing.workspace = true

[dev-dependencies]
hex-literal = "0.4"
proptest-arbitrary-interop.workspace = true

[features]
scroll = ["reth-trie/scroll"]