[package]
name = "scroll-alloy-rpc-types"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
scroll-alloy-consensus = { workspace = true, features = ["serde"] }
alloy-consensus = { workspace = true, default-features = false }
alloy-eips = { workspace = true, features = ["serde"], default-features = false }
alloy-network-primitives = { workspace = true, default-features = false }
alloy-primitives = { workspace = true, features = ["map", "rlp", "serde"], default-features = false }
alloy-rpc-types-eth = { workspace = true, features = ["serde"], default-features = false }
alloy-serde = { workspace = true, default-features = false }
arbitrary = { workspace = true, features = ["derive", "derive"], optional = true }
derive_more = { workspace = true, default-features = false }
serde = { workspace = true, features = ["derive", "alloc", "derive"], default-features = false }
serde_json = { workspace = true, features = ["alloc"], default-features = false }

[dev-dependencies]
similar-asserts = "1.6"
alloy-consensus = { workspace = true, features = ["arbitrary"], default-features = false }
alloy-primitives = { workspace = true, features = ["arbitrary"], default-features = false }
alloy-rpc-types-eth = { workspace = true, features = ["arbitrary"], default-features = false }
arbitrary = { workspace = true, features = ["derive", "derive"] }

[features]
arbitrary = [
    "std",
    "dep:arbitrary",
    "alloy-primitives/arbitrary",
    "alloy-rpc-types-eth/arbitrary",
    "scroll-alloy-consensus/arbitrary",
    "alloy-consensus/arbitrary",
    "alloy-eips/arbitrary",
    "alloy-serde/arbitrary",
]
default = ["std"]
k256 = [
    "alloy-rpc-types-eth/k256",
    "scroll-alloy-consensus/k256",
]
std = [
    "alloy-network-primitives/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "alloy-rpc-types-eth/std",
    "alloy-consensus/std",
    "alloy-serde/std",
    "derive_more/std",
    "serde/std",
    "serde_json/std",
    "scroll-alloy-consensus/std",
]
