[package]
name = "reth-scroll-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-evm.workspace = true
reth-execution-types.workspace = true
reth-primitives = { workspace = true, features = ["reth-codec"] }
reth-primitives-traits.workspace = true
reth-revm.workspace = true

# revm
revm = { workspace = true, features = ["optional_no_base_fee"] }
revm-primitives.workspace = true
revm-scroll.workspace = true

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-consensus.workspace = true
reth-scroll-forks.workspace = true
reth-scroll-primitives = { workspace = true, features = ["serde", "reth-codec"] }

# alloy
alloy-consensus.workspace = true
alloy-evm.workspace = true

# scroll
scroll-alloy-consensus.workspace = true
scroll-alloy-evm.workspace = true

# misc
derive_more.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
eyre.workspace = true
