[package]
name = "reth-scroll-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-evm = { workspace = true, features = ["scroll-alloy-traits"] }
reth-execution-types.workspace = true
reth-primitives = { workspace = true, features = ["serde-bincode-compat", "reth-codec"] }
reth-primitives-traits.workspace = true

# revm
revm = { workspace = true, features = ["optional_no_base_fee"] }
revm-primitives.workspace = true
revm-scroll.workspace = true

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-forks.workspace = true
reth-scroll-primitives = { workspace = true, features = ["serde", "serde-bincode-compat", "reth-codec"] }

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-primitives.workspace = true

# scroll
scroll-alloy-consensus.workspace = true
scroll-alloy-evm.workspace = true
scroll-alloy-hardforks.workspace = true

# misc
derive_more.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
eyre.workspace = true
alloy-primitives = { workspace = true, features = ["getrandom"] }

[features]
default = ["std"]
std = [
    "scroll-alloy-consensus/std",
    "scroll-alloy-evm/std",
    "alloy-consensus/std",
    "alloy-evm/std",
    "alloy-eips/std",
    "alloy-primitives/std",
    "derive_more/std",
    "reth-chainspec/std",
    "reth-evm/std",
    "reth-execution-types/std",
    "reth-primitives-traits/std",
    "reth-primitives/std",
    "reth-scroll-chainspec/std",
    "reth-scroll-forks/std",
    "reth-scroll-primitives/std",
    "revm-primitives/std",
    "revm-scroll/std",
    "revm/std",
    "thiserror/std",
    "tracing/std",
]
