[package]
name = "reth-scroll-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# reth
reth-chainspec.workspace = true
reth-consensus.workspace = true
reth-ethereum-consensus.workspace = true
reth-evm.workspace = true
reth-primitives.workspace = true
reth-primitives-traits.workspace = true
reth-revm.workspace = true

# revm
revm = { workspace = true, features = ["optional_no_base_fee"] }

# scroll
reth-scroll-chainspec.workspace = true
reth-scroll-forks.workspace = true

# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true

# scroll
reth-scroll-consensus.workspace = true
reth-scroll-execution.workspace = true

# misc
auto_impl.workspace = true
derive_more.workspace = true
thiserror.workspace = true
tracing.workspace = true

[dev-dependencies]
eyre.workspace = true
reth-scroll-execution = { workspace = true, features = ["test-utils"] }
reth-scroll-primitives.workspace = true

[features]
optimism = [
	"reth-primitives/optimism",
	"revm/optimism"
]
scroll = [
	"reth-chainspec/scroll",
	"reth-evm/scroll",
	"reth-primitives/scroll",
	"reth-primitives-traits/scroll",
	"reth-revm/scroll",
	"reth-scroll-consensus/scroll",
	"reth-scroll-execution/scroll",
	"revm/scroll"
]
