[package]
name = "scroll-alloy-rpc-types-engine"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
exclude.workspace = true

[lints]
workspace = true

[dependencies]
# alloy
alloy-primitives.workspace = true
alloy-rpc-types-engine.workspace = true

# misc
serde = { workspace = true, optional = true }

[dev-dependencies]
serde_json.workspace = true

[features]
serde = [
    "dep:serde",
    "alloy-primitives/serde",
    "alloy-rpc-types-engine/serde"
]
